// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

type Score struct {
	SongName    string
	ChartType   int64
	Difficulty  int64
	Achievement float64
	Genre       string
	Level       float64
}
