// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package scoresdb

type Score struct {
	SongName    string
	ChartType   string
	Difficulty  string
	Achievement int64
	FcAp        interface{}
	Sync        interface{}
	DxStar      int64
	DxPercent   int64
}
