// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package songdatadb

import (
	"database/sql"
)

type Songdatum struct {
	ID      string
	Title   string
	Artist  string
	Genre   string
	Img     string
	Release string
	Version string
	IsDx    bool
	Diff    string
	Level   string
	Const   interface{}
	IsUtage bool
	IsBuddy sql.NullString
}
